# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
    :inetRouter => {
        :box_name => "generic/centos8s",
        # :box_version => "20230710.0",
        :vm_name => "inetRouter",
        :net => [
            # auto_config, adapter, ip, netmask, virtualbox__intnet, 
            # [false, 2, "router-net"],
            # [false, 2, "router-net"],
            # ["192.168.11.10", "255.255.255.0", 8]
            {adapter: 2, auto_config: false, virtualbox__intnet: "router-net"},
            {adapter: 3, auto_config: false, virtualbox__intnet: "router-net"},
            {ip: '192.168.11.10', adapter: 8},
        ]
    },
    :cRouter => {
        :box_name => "generic/centos8s",
        # :box_version => "20230710.0",
        :vm_name => "cRouter",
        :net => [
            # auto_config, adapter, ip, netmask, virtualbox__intnet, 
            # [false, 2, "router-net"],
            # [false, 2, "router-net"],
            # ["192.168.11.10", "255.255.255.0", 8]
            {adapter: 2, auto_config: false, virtualbox__intnet: "router-net"},
            {adapter: 3, auto_config: false, virtualbox__intnet: "router-net"},
            {ip: "192.168.255.9", adapter: 6, netmask: "255.255.255.252", virtualbox__intnet: "office1-central"},
            {ip: '192.168.11.11', adapter: 8},
        ]
    },
    # :centralRouter1 => {
    #     :box_name => "generic/centos8s",
    #     # :box_name => "centos/stream8",
    #     # :box_version => "20210210.0",
    #     :vm_name => "centralRouter1",
    #     :net => [
    #         # ip, netmask, adapter, virtualbox__intnet, auto_config
    #         {adapter: 2, auto_config: false, virtualbox__intnet: "router-net"},
    #         {adapter: 3, auto_config: false, virtualbox__intnet: "router-net"},
    #         {ip: '192.168.255.9', adapter: 6, netmask: "255.255.255.252", virtualbox__intnet: "office1-central"},
    #         {ip: '192.168.11.11', adapter: 8},
    #     ]
    # },
    :office1Router => {
        :box_name => "generic/centos8s",
        # :box_name => "centos/stream8",
        # :box_version => "20210210.0",
        :vm_name => "office1Router",
        :net => [
            # ip, netmask, adapter, virtualbox__intnet, auto_config
            {ip: "192.168.255.10", adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "office1-central"},
            {adapter: 3, auto_config: false, virtualbox__intnet: "vlan1"},
            {adapter: 4, auto_config: false, virtualbox__intnet: "vlan1"},
            {adapter: 5, auto_config: false, virtualbox__intnet: "vlan2"},
            {adapter: 6, auto_config: false, virtualbox__intnet: "vlan2"},
            {ip: '192.168.11.20', adapter: 8},
        ]
    },
    :testClient1 => {
        :box_name => "generic/centos8s",
        # :box_name => "centos/stream8",
        # :box_version => "20210210.0",
        :vm_name => "testClient1",
        :net => [
            # ip, netmask, adapter, virtualbox__intnet, auto_config
            {adapter: 2, auto_config: false, virtualbox__intnet: "testLAN"},
            {ip: '192.168.11.21', adapter: 8},
        ]
    },
    :testServer1 => {
        :box_name => "generic/centos8s",
        # :box_name => "centos/stream8",
        # :box_version => "20210210.0",
        :vm_name => "testServer1",
        :net => [
            # ip, netmask, adapter, virtualbox__intnet, auto_config
            {adapter: 2, auto_config: false, virtualbox__intnet: "testLAN"},
            {ip: '192.168.11.22', adapter: 8},
        ]
    },
    :testClient2 => {
        :box_name => "ubuntu/focal64",
        :box_version => "20220411.2.0",
        :vm_name => "testClient2",
        :net => [
            # ip, netmask, adapter, virtualbox__intnet, auto_config
            {adapter: 2, auto_config: false, virtualbox__intnet: "testLAN"},
            {ip: '192.168.11.31', adapter: 8},
        ]
    },
    :testServer2 => {
        :box_name => "ubuntu/focal64",
        :box_version => "20220411.2.0",
        :vm_name => "testServer2",
        :net => [
            # ip, netmask, adapter, virtualbox__intnet, auto_config
            {adapter: 2, auto_config: false, virtualbox__intnet: "testLAN"},
            {ip: '192.168.11.32', adapter: 8},
        ]
    }
}

Vagrant.configure("2") do |config|
    MACHINES.each do |boxname, boxconfig|
        config.vm.define boxname do |box|
            box.vm.box = boxconfig[:box_name]
            box.vm.host_name = boxconfig[:vm_name]
            box.vm.box_version = boxconfig[:box_version]

            config.vm.provider "virtualbox" do |v|
                v.memory = 1024
                v.cpus = 1
            end

            # if boxconfig[:vm_name] == "testServer2"
            #     box.vm.provision "ansible" do |ansible|
            #         ansible.palybook = "ansible/provision.yml"
            #         ansible.inventory_path = "ansible/hosts"
            #         ansible.host_key_checking = "false"
            #         ansible.become = "true"
            #         ansible.limit = "all"
            #     end
            # end
            
# ip, netmask, adapter, virtualbox__intnet, auto_config

            boxconfig[:net].each do |ipconf|
                # box.vm.network("private_network", ip: ipconf[0], netmask: ipconf[1], adapter: ipconf[2], virtualtbox__intnet: ipconf[3], auto_config: ipconf[4])
                box.vm.network "private_network", ipconf
                # box.vm.network ipconf
            end

            box.vm.provision "shell", inline: <<-SHELL
                mkdir -p ~root/.ssh
                cp ~vagrant/.ssh/auth* ~root/.ssh
            SHELL
        end
    end
end