# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :"pam" => {
    :box_name => "generic/centos8s",
    #:box_version => "20210210.0",
    :cpus => 2,
    :memory => 1024,
    :ip => "192.168.11.10",
  }
}
Vagrant.configure("2") do |config|
    MACHINES.each do |boxname, boxconfig|
        config.vm.synced_folder ".", "/vagrant", disabled: true
        config.vm.network "private_network", ip: boxconfig[:ip]
        config.vm.define boxname do |box|
            box.vm.box = boxconfig[:box_name]
            box.vm.box_version = boxconfig[:box_version]
            box.vm.host_name = boxname.to_s

            box.vm.provider "virtualbox" do |v|
                v.memory = boxconfig[:memory]
                v.cpus = boxconfig[:cpus]
            end
            box.vm.provision "file", source: "files/login.sh", destination: "/tmp/login.sh"
            box.vm.provision "file", source: "files/sshd", destination: "/tmp/sshd"
            box.vm.provision "file", source: "files/48-docker.rules", destination: "/tmp/48-docker.rules"
            box.vm.provision "shell", inline: <<-SHELL
              sed -i 's/^PasswordAuthentication.*$/PasswordAuthentication yes/' /etc/ssh/sshd_config
              systemctl restart sshd.service
              sudo useradd otusadm && sudo useradd otus
              echo "Otus2022!" | sudo passwd --stdin otusadm && echo "Otus2022!" | sudo passwd --stdin otus
              sudo groupadd -f admin
              sudo usermod otusadm -a -G admin && sudo usermod root -a -G admin && sudo usermod vagrant -a -G admin
              sudo cp /tmp/login.sh /usr/local/bin/login.sh
              sudo chmod +x /usr/local/bin/login.sh
              sudo cp /tmp/sshd /etc/pam.d/sshd
              sudo chown root:root /etc/pam.d/sshd
              sudo cp /tmp/48-docker.rules /etc/polkit-1/rules.d/48-docker.rules
              sudo chown root:root /etc/polkit-1/rules.d/48-docker.rules
              sudo service polkit restart
            SHELL
            
        end
    end
end