# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
    config.vm.box = "centos/7lvm"

    config.vm.provider "virtualbox" do |v|
        v.memory = 256
        v.cpus = 1
    end
    config.vm.define "grub" do |grub|
        grub.vm.network "private_network",ip:"192.168.11.10",virtualbox_intnet:"net1"
        grub.vm.hostname = "grub"
    end
end