# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
    config.vm.box = "generic/centos8s"


    config.vm.provider "virtualbox" do |v|
        v.memory = 256
        v.cpus = 1
    end
    config.vm.define "rpms" do |rpms|
        rpms.vm.network "private_network",ip:"192.168.11.10",virtualbox_intnet:"net1"
        rpms.vm.hostname = "rpms"
        rpms.vm.provision "shell", path: "repo.sh"
    end
end