MACHINES = {
    :router1 => {
        :box_name => "generic/ubuntu2204",
        :vm_name => "router1",
        :net => [
            ["10.0.10.1", 2, "255.255.255.252", "r1-r2"],
            ["10.0.12.1", 3, "255.255.255.252", "r1-r3"],
            ["192.168.10.1", 4, "255.255.255.0", "net1"],
            ["192.168.11.10", 5, "255.255.255.0"],
            # {ip: '10.0.10.1', adapter: 2, netmask: "255.255.255.252", virtualbox__inet: "r1-r2"},
            # {ip: '10.0.12.1', adapter: 3, netmask: "255.255.255.252", virtualbox__inet: "r1-r3"},
            # {ip: '192.168.10.1', adapter: 4, netmask: "255.255.255.0", virtualbox__inet: "net1"},
            # {ip: '192.168.11.10', adapter: 5, netmask: "255.255.255.0"},
        ]
    },
    :router2 => {
        :box_name => "generic/ubuntu2204",
        :vm_name => "router2",
        :net => [
            ["10.0.10.2", 2, "255.255.255.252", "r1-r2"],
            ["10.0.11.2", 3, "255.255.255.252", "r2-r3"],
            ["192.168.20.1", 4, "255.255.255.0", "net2"],
            ["192.168.11.11", 5, "255.255.255.0"],
            # {ip: '10.0.10.2', adapter: 2, netmask: "255.255.255.252", virtualbox__inet: "r1-r2"},
            # {ip: '10.0.11.2', adapter: 3, netmask: "255.255.255.252", virtualbox__inet: "r2-r3"},
            # {ip: '192.168.20.1', adapter: 4, netmask: "255.255.255.0", virtualbox__inet: "net2"},
            # {ip: '192.168.11.11', adapter: 5, netmask: "255.255.255.0"},
        ]
    },
    :router3 => {
        :box_name => "generic/ubuntu2204",
        :vm_name => "router3",
        :net => [
            ["10.0.11.1", 2, "255.255.255.252", "r2-r3"],
            ["10.0.12.2", 3, "255.255.255.252", "r1-r3"],
            ["192.168.30.1", 4, "255.255.255.0", "net3"],
            ["192.168.11.12", 5, "255.255.255.0"],
            # {ip: '10.0.11.1', adapter: 2, netmask: "255.255.255.252", virtualbox__inet: "r2-r3"},
            # {ip: '10.0.12.2', adapter: 3, netmask: "255.255.255.252", virtualbox__inet: "r1-r3"},
            # {ip: '192.168.30.1', adapter: 4, netmask: "255.255.255.0", virtualbox__inet: "net3"},
            # {ip: '192.168.11.12', adapter: 5, netmask: "255.255.255.0"},
        ]
    }
}

Vagrant.configure("2") do |config|
    MACHINES.each do |boxname, boxconfig|
        config.vm.define boxname do |box|
            box.vm.box = boxconfig[:box_name]
            box.vm.host_name = boxconfig[:vm_name]

            box.vm.provider "virtualbox" do |v|
                v.memory = 2048
                v.cpus = 1
            end

            if boxconfig[:vm_name] == "router3"
                box.vm.provision "ansible" do |ansible|
                    ansible.playbook = "ansible/provision.yml"
                    ansible.inventory_path = "ansible/hosts"
                    ansible.host_key_checking = "false"
                    ansible.limit = "all"
                end
            end

            boxconfig[:net].each do |ipconf|
                # box.vm.network ipconf
                box.vm.network("private_network", ip: ipconf[0], adapter: ipconf[1], netmask: ipconf[2], virtualbox__intnet: ipconf[3])
            end
        end
    end
end